### ISSUE TITLE
check updated documentation

### ISSUE THREAD

**Issue by forty-rachel** [FoodStandardsAgency/lit-fetch#63]
I have updated the welcome page to reflect:
- PubMed has set up their API search (i.e. how the tool searches the data) such that the wildcard character will expand to match any set of characters up to a limit of 600 unique expansions. This means that words that have more than 600 extensions (i.e. cat*) will not return all results. As an example if the limit was in fact 3 not 600, “cat*” could expand to include “cats”, “category” and “categories” but then it would hit the limit and titles with “cathartic” in would not be captured
- I have changed the tool to read in all documents up to but not including the day of the search. 
- I am no longer filtering out publications that are missing a year of publication or a doi. Where year of publication is missing I have given them the default "1990"

I have updated the documentation page to contain information about Scopus abstracts.

Can you check that the above is all captured and there are no contradictions

**Comment by xavier-gilbert** [comment]
@forty-rachel 

bullet point 1:
* appears in doc
* would be worth mentioning that it is a globular search pattern and if regex are also available
* cannot be tested just from output, suggestion: download data, dump as continuous text, extract all words pattern cats.*, and count occurences

bullet point 2: 
* appears in welcome
* does not work as expected, see related [issue 64](https://github.com/FoodStandardsAgency/lit-fetch/issues/64)
* "You can also select the date from which you want to see articles." suggests from which we want to see (display result), not query, while the tool says "Find articles online since" so it excludes from search.

bullet point 3:
* working as expected
* "TO NOTE: where month and day of publication are not provided 01 is used as a default. Where year of publication is not provided 1990 is used as a default. This means that all publications that only provide the year of publication are given the publication date 01/01/year in our output and those that have no details are given the date 01/01/1990": works but, this detail is hidden in the "welcome/download", it should come up and be emphasised. 

Remarks (personal and on first impressions of the app):
* rail menu is not clear, Welcome is partially a documentation (it actually says more than the documentation itself about how it works)
* an example of search and or screenshots would work well
* the documentation is not a documentation, it gives sources (should be in welcome)
* since the app is based on a collection of REST APIs, and that the functions are wrapping around REST vocabulary (e.g. `get_`) the documentation should reflect this. E.g. "Fields in the returned data": it is unclear to the user if they are the fields in the response (from the queries) or from the presented output.
* "URL: Link that will take you to the article page ...", slightly confusing, should the user expect an anchor returned in the response or a string? (it seems to be string in the table)

Formatting:
"to search for multiple terms: botulism AND sheep will return everything containing the word botulism if it also contains the word sheep", feels cluttered to the user, should use other font to better set appart
* "TO NOTE" is sometimes all caps, sometimes "To note".
* "If the above search returned an error please check that you have closed all your brackets. Some special characters (i.e. &) may also cause errors." This message should only pop up when the query returns an error.
* why are the filters split in 3 fields and not simply following the same UX as for the search (confusing imo)

**Comment by forty-rachel** [comment]
bullet 1: I reckon one way to test in tool is see if you get a larger return if you use more specific wild cards. If: 
"medica* AND medici*" 
returns more results then 
"medic*" 
you'll know that "medic" is not returning everything

**Comment by xavier-gilbert** [comment]
Ok, I was thinking too far into not only validating the limit but also that it is 600 :D

Limit is applied:

medici* | 89377
-- | --
medica* | 204952
  | 294329
  |  
medic* | 269306
  | 25023
