### ISSUE TITLE
check date for defaults

### ISSUE THREAD

**Issue by forty-rachel** [FoodStandardsAgency/lit-fetch#64]
three data sources are read in - I have changed the default for them all so that they read in data up to but not including the day of the search - can you check that the dates are adjusted in the correct places. 

Can you also check the download contains the correct dates on the search details tab

**Comment by xavier-gilbert** [comment]
@forty-rachel 

1) returns publication that are past the day of the search
database: Pubmed (only)
search term: nuts
find articles online since: 2019-01-01
allowed number of results: 1400
total results returned: 1105
filters: defaults (all publication type, no word)

![image](https://user-images.githubusercontent.com/72391862/100452450-14213f80-30b1-11eb-9d2a-c9ad0607a357.png)

Potential issues:
* app is not filtering properly and returns the full results
* date parsing
* API incorrect date field

2) parenthesis matching
Working, returns message and does not perform seach.
Warning/error message barely visible, not great for UX

Suggested change: warning messages are commonly displayed in italics, possibly red, above or below the field that contains an error + field highlighted / toggled in

**Comment by forty-rachel** [comment]
This is a result of searching on publication date not electronic publication date (edat vs pdat https://pubmed.ncbi.nlm.nih.gov/help/#pubmedhelp.Advanced_Search). Edat may make more sense for reproducibility, however pdat aligns with the website. One to consider

**Comment by xavier-gilbert** [comment]
I am not sure how this results in a publication date of "2021-02-05" and then if that is expected (as I understand from your message above). Yet the result is not filtered out on "up to today, day of search" as doc suggests and as the issue asked to QA?

I believe your point about edat and pdat, is important and should appear in the doc? I would assume a very small proportion of user to dig it from the pubmed api doc, also as there is no indication of that in the column name?

**Comment by forty-rachel** [comment]
have updated the documentation to be more clear about use of dates
