### ISSUE TITLE
EBSCO - acaemic journal = review and journal article can we keep in when either one or other is ticked

### ISSUE THREAD

**Issue by forty-rachel** [FoodStandardsAgency/lit-fetch#83]

**Comment by xavier-gilbert** [comment]
if it says it is an academic then it could be a review and and article so if ebsco says academic journal and we only have an ebsco record for that and ...

if article (publication type) is ebsco then in the pub type it will be review/journal article. adjust the filter so that the column has "review" term in the pub type for example.

**Comment by xavier-gilbert** [comment]
setup the search so that ebsco is the least important one?
